name: Publish Release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup MsBuild
        uses: microsoft/setup-msbuild@v1

      - name: Generate Certificate
        run: powershell.exe -f generate_cert.ps1

      - name: Build Release
        run: msbuild.exe /nologo /m /t:Rebuild /p:Configuration=Release ppl_runner.sln

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Build - PPLRunner
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/x64/Release/ppl_runner.exe
          asset_name: ppl_runner.exe
          asset_content_type: application/octet-stream

      - name: Upload Build - ChileExample
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/x64/Release/child_example.exe
          asset_name: child_example.exe
          asset_content_type: application/octet-stream

      - name: Upload Build - ELAMDriver
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/x64/Release/elam_driver.sys
          asset_name: elam_driver.sys
          asset_content_type: application/octet-stream

      - name: Upload Cert
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ppl_runner.pfx
          asset_name: ppl_runner.pfx
          asset_content_type: application/octet-stream
